---
title: Trabajos
lang: es
---

## Evaluación

La presente evaluación tiene por objetivo que las y los estudiantes apliquen de forma integral los contenidos del curso a una temática de interés específica utilizando la base de datos del Estudio Social Longitudinal de Chile (ELSOC) 2022, en formato de reporte de investigación breve. Se espera un ejercicio de investigación que logre dar cuenta del aprendizaje de las herramientas de análisis estadístico que configuran las habilidades básicas para desarrollar procesos de investigación social, analizando fuentes de información de carácter cuantitativo desde una perspectiva sociológica.

En este informe, los estudiantes deberán elaborar un reporte de investigación que desarrolle de forma integrada los aspectos de diseño de la investigación, análisis estadístico y presentación de resultados, así como la elaboración de conclusiones.

Cuestiones a considerar:

1.  El trabajo debe ser realizado en parejas
2.  Se realizará **una entrega final** tipo **reporte de investigación**, que se irá construyendo a lo largo del semestre
3.  Se recomienda que elaboren un problema de investigación que trate sobre las características sociales de algún **problema actual de la sociedad chilena**, y que sea factible de investigar con los datos del Estudio Social Longitudinal de Chile (ELSOC) 2022.
4.  La investigación a desarrollar debe ser de tipo **descriptiva**, esto quiere decir que se trata de una pregunta de investigación que se refiere a la forma, magnitud o características que tienen unas determinadas variables en una población.

## Instrucciones

Para la entrega del informe se espera que, habiendo seleccionado un fenómeno específico de interés, se desarrollen los siguientes puntos:

+--------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------+
| **COMPONENTES**                                        | **DETALLE**                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         | **PUNTAJE** |
+--------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------+
| **Formulación del problema**                           | **Fundamente el interés sociológico que habilita el estudio de la temática elegida** (¿Qué se va a estudiar?, ¿Por qué es importante?, ¿Qué se sabe sobre el tema?), utilizando al menos 3 referencias bibliográficas. Además, **formule una pregunta y un objetivo general de investigación.** Estos deben ser coherentes entre sí y con la formulación del problema expuesta en el apartado anterior. El objetivo de investigación formulado debe permitir entender cómo se analizará la temática elegida. Además, la pregunta debe ser de carácter descriptiva. **(1 plana)**                                                                                                                                                    | 1,0         |
+--------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------+
| \                                                      | **Defina la fuente de información a utilizar** indicando el nombre de la base de datos y la institución que la disponibiliza, la población que busca representar el estudio, el procedimiento de muestreo utilizado y el tamaño de la muestra. Dado que trabajaremos solo con el Estudio Social Longitudinal de Chile (ELSOC) 2022, se espera que los grupos describan qué busca medir y representar el módulo de la encuesta elegido. **(½ plana)**                                                                                                                                                                                                                                                                                | 0,5         |
|                                                        |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     |             |
| **Definición base de datos**                           |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     |             |
+--------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------+
| \                                                      | **Seleccionar un mínimo de 4 variables** para, mediante su estudio, responder a la pregunta de investigación. Todas las variables deben remitir al tema de interés: 2 de las variables deben ser de nivel de medición de intervalo o razón, 1 variable debe ser de nivel de medición ordinal y 1 variable debe ser de nivel de medición nominal, además, un conjunto de variables para armar una escala o índice.                                                                                                                                                                                                                                                                                                                   | 2,0         |
|                                                        |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     |             |
| **Definición variables a utilizar**                    | Para cada variable debe indicar: i) una breve descripción que especifique el nivel de medición de la  variable, su nombre en la base de datos y el fraseo en la encuesta, ii) explique qué aspecto del fenómeno de interés representa y iii) su utilidad para resolver la pregunta de investigación. La selección de variables debe ser coherente con la formulación del problema y la pregunta y objetivos de investigación propuestos. **(1 plana)**                                                                                                                                                                                                                                                                              |             |
+--------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------+
| **Tablas de frecuencia**                               | **Calcular una tabla de frecuencia** (absoluta y relativa) para las variables nominales y ordinales e interpretar. La interpretación de tablas debe buscar aportar con elementos que permitan construir una respuesta a la pregunta y objetivos de investigación. Los cálculos deben ser realizados en R.                                                                                                                                                                                                                                                                                                                                                                                                                           | 2,0         |
+--------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------+
| **Medidas de tendencia central**                       | **Calcular e interpretar las medidas de tendencia central** (estadístico muestral) para las variables intervalares y de razón seleccionadas. Colocarlas en una tabla. La interpretación debe ser relevante para responder la pregunta y objetivo de investigación. Los cálculos deben ser realizados en R.                                                                                                                                                                                                                                                                                                                                                                                                                          | 2,0         |
+--------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------+
| **Medidas de dispersión**                              | **Calcular el rango, la desviación estándar y el coeficiente de variación** (estadístico muestral) para las variables intervalares y de razón seleccionadas. Colocarlas en una tabla. La interpretación debe ser relevante para responder la pregunta y objetivo de investigación. Los cálculos deben ser realizados en R.                                                                                                                                                                                                                                                                                                                                                                                                          | 2,0         |
+--------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------+
| **Medidas de posición**                                | **Calcular el valor mínimo y máximo, el cuartil 1 y el cuartil 3** (estadístico muestral) para las variables intervalares y de razón seleccionadas. Colocarlas en una tabla. La interpretación debe ser relevante para responder la pregunta y objetivo de investigación. Los cálculos deben ser realizados en R.                                                                                                                                                                                                                                                                                                                                                                                                                   | 2,0         |
+--------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------+
| **Gráficos**                                           | **Presentar al menos 2 gráficos** seleccionando para su construcción aquellas variables más relevantes para el problema de investigación. La interpretación debe ser relevante para responder la pregunta y objetivo de investigación. Los gráficos deben ser realizados en R.                                                                                                                                                                                                                                                                                                                                                                                                                                                      | 2,0         |
+--------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------+
| **Índices y escalas**                                  | **Construir al menos un índice o escala** a partir del conjunto de variables seleccionado. Este índice o escala debe reportar e interpretar el nivel de consistencia interna de las variables                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       | 2,0         |
+--------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------+
| **Estimación puntual, intervalo de confianza y error** | **Calcular los parámetros e intervalos de confianza para dos de las variables seleccionadas**. Además, debe elaborar una tabla resumen que sintetice todos los indicadores que considere relevantes para interpretar la información. La interpretación debe ser relevante para responder la pregunta y objetivo de investigación. Los cálculos deben ser realizados en R.                                                                                                                                                                                                                                                                                                                                                           | 2,0         |
+--------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------+
| **Conclusiones**                                       | En las conclusiones se deben **sintetizar los aspectos más relevantes de los análisis estadísticos ya expuestos**, articulando toda la información trabajada debe presentarse una respuesta tentativa a la pregunta de investigación. Este resumen de los resultados, así como las conclusiones, **deben dialogar con lo planteado en la introducción de su trabajo**, haciendo referencia a las fuentes bibliográficas utilizadas en la presentación del problema de investigación. Además, debe reflexionar sobre los límites de su diseño de investigación y señalar posibles ejes de investigación que podrían ser considerados en futuras indagaciones. Se valorará la pertinencia sociológica de la conclusión **(1 plana).** | 2,0         |
+--------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------+
| **Trabajo en R**                                       | Además del informe, entregar la carpeta con el Proyecto R, que contenga un archivo .Rproject, y las carpetas input, procesamiento y output.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         | 3,0         |
|                                                        |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     |             |
|                                                        | -   La carpeta input debe contener la base de datos, manual de usuario, libro de códigos.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           |             |
|                                                        |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     |             |
|                                                        | -   La carpeta procesamiento debe contener un archivo de sintaxis para el procesamiento y otro para el análisis de los datos.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       |             |
|                                                        |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     |             |
|                                                        | -   La carpeta output debe contener la base de datos procesada y el resto de salidas asociadas (tablas, gráficos, etc.).                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            |             |
|                                                        |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     |             |
|                                                        | Se evaluará que los códigos utilizados generen las salidas (tablas, gráficos, etc.) que se presentan en el informe.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 |             |
+--------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------+

# **Aspectos formales**

Para la construcción del reporte de investigación por favor considere: 

-   El trabajo debe tener una portada que incluya: título, logo de la universidad, nombre de los estudiantes, profesor/a, fecha y ayudantes. 

-   Debe incluirse un índice. Tablas, referencias y bibliografía utilizada debe presentarse en  formato APA. 

-   La fuente a utilizar debe ser Letra Times New Roman 12**, interlineado simple y justificado**. Notas a pie de página en tamaño 10, en mismo formato que el texto central. 

-   El trabajo debe tener una redacción adecuada y sin errores de ortografía. 

-   Se descontarán **hasta 5 décimas** sobre la nota final por errores de este tipo. 

## Fecha y formato de entrega

El formato de entrega del informe debe ser un documento en **formato PDF (.pdf),** que debe estar alojado en la carpeta output del Proyecto R. Fecha de entrega: viernes 12 de julio hasta las 23:59 vía módulo Tareas en plataforma U-Cursos. 

-   Entregas atrasadas hasta las 23:59 del sábado 13 de julio tendrán 0,5 puntos de descuento  sobre la nota final. 

-   Entregas atrasadas hasta el domingo 14 de julio hasta las 23:59 tendrán 1,0 punto de descuento sobre la nota final. No serán evaluadas entregas posteriores a esta fecha. 

## Sobre plagio

Todos los trabajos se procesan en software para detección de plagio: evidencia de una situación de plagio implica obtención de la nota mínima en la evaluación (1,0) junto con constituirse como causal de reprobación de la asignatura.

## Recomendaciones para la entrega

-   Máxima de escritura: una idea por párrafo. Si comienza una idea nueva, se recomienda comenzar otro párrafo. Al revés, si el párrafo siguiente habla de lo mismo, sumarlo al párrafo anterior. 

-   La idea del párrafo se resume en la primera parte del párrafo, lo que en inglés se llama "topic sentence". 

-   Declarar domicilio disciplinar: ej, mencionar la palabra "sociología" en el primer/segundo párrafo, esto fuerza que la investigación se enmarque en la disciplina.

En caso de tener dudas, no dude en contactar a sus ayudantes respectivos, o bien, vía foro U-Cursos al equipo docente de la asignatura.
